site:
  title: Javowiec.dev
  url: https://javowiec.dev
  start_page: reference::index.adoc
content:
  sources:
    - url: https://github.com/p-marcin/dev-cheat-sheets.git
      branches: [main, feature/*]
      start_path: docs
      edit_url: '{web_url}/blob/{refname}/{path}'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    icons: font
