= Spring WebMVC Test

image:https://img.shields.io/badge/Spring%20WebMVC%20Test%20Docs-2088E9?logo=quickLook&logoColor[link="{spring-framework-docs}/testing/mockmvc.html",window=_blank]
image:https://img.shields.io/badge/Spring%20Boot%20WebMVC%20Test%20Docs-2088E9?logo=quickLook&logoColor[link="{spring-boot-docs}/reference/testing/spring-boot-applications.html#testing.spring-boot-applications.spring-mvc-tests",window=_blank]

== Overview

Spring MVC Controllers are tricky to test properly. They have a high degree of integration with Spring MVC framework. JUnit tests are not sufficient to test the framework interaction.

Spring Boot supports a concept of *Test Splices* which bring up a targeted segment of the autoconfigured Spring Boot environment:

* e.g. just the Database components or just the Web components,
* user defined Spring beans typically are not initialized.

== WebMvcTest

{spring-boot-api-docs}/org/springframework/boot/test/autoconfigure/web/servlet/WebMvcTest.html[`@WebMvcTest`^]::
A Spring Boot test splice which creates a MockMVC environment for the Controller under a test. Dependencies of it are not included and need to be added to the Spring Context in the test environment.
+
TIP: `@WebMvcTest` will autoconfigure *all the Controllers*. If you want to autoconfigure only specific Controllers, use it like: `@WebMvcTest(BookController.class)`

{spring-framework-api-docs}/org/springframework/test/web/servlet/MockMvc.html[`🔴 MockMvc`^]::
Main entry point for server-side Spring MVC test support.
+
.In `@WebMvcTest` you can autowire `🔴 MockMvc`
[,java]
----
@Autowired
MockMvc mockMvc;
----

== Testing Controller requests

{spring-framework-api-docs}/org/springframework/test/web/servlet/request/MockMvcRequestBuilders.html[`🟠 MockMvcRequestBuilders`^]::
Static factory methods for building {spring-framework-api-docs}/org/springframework/mock/web/MockHttpServletRequest.html[`🟢 MockHttpServletRequest`^] which is mock implementation of the {jakarta-ee-api-docs}/jakarta/servlet/http/httpservletrequest[`⚪ HttpServletRequest`^].

{spring-framework-api-docs}/org/springframework/test/web/servlet/result/MockMvcResultMatchers.html[`🟠 MockMvcResultMatchers`^]::
Static factory methods for building {spring-framework-api-docs}/org/springframework/test/web/servlet/ResultMatcher.html[`⚪ ResultMatcher`^]-based result actions. A `⚪ ResultMatcher` matches the result of an executed request against some expectation.
+
.Test Controller GET request
[,java]
----
mockMvc.perform(MockMvcRequestBuilders.get("/api/v1/book/{bookId}", testBookDTO.getId())
        .accept(MediaType.APPLICATION_JSON))
    .andExpect(MockMvcResultMatchers.status().isOk())
    .andExpect(MockMvcResultMatchers.content().contentType(MediaType.APPLICATION_JSON));
----
+
--
.Test Controller POST request
[,java]
----
mockMvc.perform(MockMvcRequestBuilders.post("/api/v1/book")
        .accept(MediaType.APPLICATION_JSON)
        .contentType(MediaType.APPLICATION_JSON)
        .content(objectMapper.writeValueAsString(testBookDTO))) // <1>
    .andExpect(MockMvcResultMatchers.status().isCreated())
    .andExpect(MockMvcResultMatchers.header().exists(HttpHeaders.LOCATION));
----
<1> Converts `testBookDTO` into JSON with xref:spring-framework:spring-boot-test.adoc#_fasterxml_jackson[FasterXML Jackson]
--
+
.Test Controller PUT request
[,java]
----
mockMvc.perform(MockMvcRequestBuilders.put("/api/v1/book/{bookId}", testBookDTO.getId())
        .accept(MediaType.APPLICATION_JSON)
        .contentType(MediaType.APPLICATION_JSON)
        .content(objectMapper.writeValueAsString(testBookDTO)))
    .andExpect(MockMvcResultMatchers.status().isNoContent());
----
+
.Test Controller PATCH request
[,java]
----
Map<String, Object> bookMap = new HashMap<>();
bookMap.put("name", "New Book Name");
mockMvc.perform(MockMvcRequestBuilders.patch("/api/v1/book/{bookId}", testBookDTO.getId())
        .accept(MediaType.APPLICATION_JSON)
        .contentType(MediaType.APPLICATION_JSON)
        .content(objectMapper.writeValueAsString(bookMap)))
    .andExpect(MockMvcResultMatchers.status().isNoContent());
----
+
.Test Controller DELETE request
[,java]
----
mockMvc.perform(MockMvcRequestBuilders.delete("/api/v1/book/{bookId}", testBookDTO.getId())
        .accept(MediaType.APPLICATION_JSON)
    .andExpect(MockMvcResultMatchers.status().isNoContent());
----

=== Mocking Beans

{spring-framework-api-docs}/org/springframework/test/context/bean/override/mockito/MockitoBean.html[`@MockitoBean`^]::
Can be used in test classes to override a bean in the test's `⚪ ApplicationContext` with a Mockito mock. For example a Service which is called by Controller.
+
--
.Return an object on given method call
[,java]
----
@MockitoBean
BookService bookService;

@Test
void testGetBookById() throws Exception {
    BookDTO testBookDTO = // ...
    BDDMockito.given(bookService.getBookById(ArgumentMatchers.any(UUID.class))) // <1> <2>
        .willReturn(testBookDTO);
    // ...
}
----
<1> {mockito-api-docs}/org/mockito/BDDMockito.html[`🟢 BDDMockito`^] -
Behavior Driven Development style of writing tests uses `//given` `//when` `//then` comments as fundamental parts of your test methods.
<2> {mockito-api-docs}/org/mockito/ArgumentMatchers.html[`🟢 ArgumentMatchers`^] - allows flexible verification or stubbing. For example `any()` matches anything, including nulls, while `any(Class<T> type)` matches any object of given type, excluding nulls.
--
+
--
.Verify that behavior happened once
[,java]
----
Mockito.verify(bookService).updateBookById(ArgumentMatchers.any(UUID.class), ArgumentMatchers.any(BookDTO.class)); // <1>
----
<1> {mockito-api-docs}/org/mockito/Mockito.html#verify(java.lang.Object)[`🟢 Mockito#verify(T mock)`^] - verifies certain behavior happened once. It is alias to: `verify(mock, Mockito.times(1)).someMethod("some arg");`.
--
+
--
.Capture and assert arguments
[,java]
----
@Captor // <1>
ArgumentCaptor<UUID> uuidArgumentCaptor;

@Test
void testDeleteBookById() throws Exception {
    BookDTO testBookDTO = // ...
    // ...
    Mockito.verify(bookService).deleteBookById(uuidArgumentCaptor.capture());
    Assertions.assertThat(testBookDTO.getId()).isEqualTo(uuidArgumentCaptor.getValue()); // <2>
}
----
<1> {mockito-api-docs}/org/mockito/Captor.html[`@Captor`^] - allows shorthand {mockito-api-docs}/org/mockito/ArgumentCaptor.html[`🟢 ArgumentCaptor`^] creation on fields (instead of `ArgumentCaptor<UUID> uuidArgumentCaptor = ArgumentCaptor.forClass(UUID.class)`).
<2> {assertj-core-api-docs}/org/assertj/core/api/Assertions.html[`🟢 Assertions`^] - AssertJ entry point for assertion methods for different types. Each method in this class is a static factory for a type-specific assertion object.
--
+
.Throw an exception on given method call
[,java]
----
BDDMockito.given(bookService.getBookById(ArgumentMatchers.any(UUID.class)))
        .willThrow(NotFoundException.class);
----

=== Jayway JsonPath

image:https://img.shields.io/badge/Jayway%20JsonPath%20Docs-2088E9?logo=quickLook&logoColor=white[link="{jayway-jsonpath-docs}",window=_blank]

A Java DSL (Domain Specific Language) for *reading JSON documents*. It is *included* in Spring Boot Test dependency. Useful for *performing assertions against the JSON object* that is coming back from `🔴 MockMvc`.

.JsonPath expressions can use the dot-notation:
[,json]
----
$.store.book[0].title
----

.or the bracket-notation:
[,json]
----
$['store']['book'][0]['title']
----

.Example of `🔴 MockMvc` json path validation
[,java]
----
.andExpect(MockMvcResultMatchers.jsonPath("$.content[1].id", Is.is("some-id-123"))) // <1>
.andExpect(MockMvcResultMatchers.jsonPath("$.content.length()", Is.is(3))); // <2>
----
<1> {hamcrest-api-docs}/org/hamcrest/core/Is.html#is(T)[`🟢 Is#is(T value)`^] - matcher from JavaHamcrest which is a shortcut to the frequently used `is({hamcrest-api-docs}/org/hamcrest/core/IsEqual.html#equalTo(T)[equalTo(x)^])` (where {hamcrest-api-docs}/org/hamcrest/core/Is.html#is(org.hamcrest.Matcher)[`is(Matcher<T> matcher)`^] only decorates another matcher).
<2> Asserts that we have 3 objects in `content` array.

== Testing Exception Handling

.Test 404 HTTP Response Code
[,java]
----
mockMvc.perform(MockMvcRequestBuilders.get("/api/v1/book/{bookId}", UUID.randomUUID()))
    .andExpect(status().isNotFound());
----
