= Spring Data JPA Test

image:https://img.shields.io/badge/Spring%20Boot%20Data%20JPA%20Test%20Docs-2088E9?logo=quickLook&logoColor[link="{spring-boot-docs}/reference/testing/spring-boot-applications.html#testing.spring-boot-applications.autoconfigured-spring-data-jpa",window=_blank]

== DataJpaTest

{spring-boot-api-docs}/org/springframework/boot/test/autoconfigure/orm/jpa/DataJpaTest.html[`@DataJpaTest`^]::
A Spring Boot test splice which creates a JPA environment for the Repository under a test. Dependencies of it are not included and need to be added to the Spring Context in the test environment.
+
TIP: By default, tests annotated with `@DataJpaTest` are *transactional* and *roll back at the end of each test*. They also use an *embedded in-memory database* (replacing any explicit or usually auto-configured DataSource).

{spring-framework-api-docs}/org/springframework/context/annotation/Import.html[`@Import`^]::
Indicates one or more component classes to import - typically `@Configuration` classes.

== Testing Repository methods

[,java]
----
@Autowired
BookRepository bookRepository;

@Test
void testSaveBook() {
    Book savedBook = bookRepository.save(Book.builder()
            .name("My Book")
            .price(new BigDecimal("11.99"))
            .build());

    bookRepository.flush(); // <1>

    assertThat(savedBook).isNotNull();
    assertThat(savedBook.getId()).isNotNull(); // <2>
}
----
<1> {spring-data-jpa-api-docs}/org/springframework/data/jpa/repository/JpaRepository.html#flush()[`⚪ JpaRepository<T,ID>#flush()`^] flushes all pending changes to the database.
<2> Id will be generated by Hibernate.
