= Spring Boot Test

image:https://img.shields.io/badge/Spring%20Documentation-2088E9?logo=quickLook&logoColor[link="https://docs.spring.io/spring-framework/reference/testing.html",window=_blank]
image:https://img.shields.io/badge/Spring%20Boot%20Documentation-2088E9?logo=quickLook&logoColor[link="https://docs.spring.io/spring-boot/reference/testing/index.html",window=_blank]

== Maven Dependency

[,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <scope>test</scope>
</dependency>
----

== Spring Boot Test

{spring-boot-api-spec-url}/org/springframework/boot/test/context/SpringBootTest.html[`@SpringBootTest`^]::
Annotation that can be specified on a test class that runs Spring Boot based tests. Provides the following features over and above the regular Spring TestContext Framework:
* Uses {spring-boot-api-spec-url}/org/springframework/boot/test/context/SpringBootContextLoader.html[`🟢 SpringBootContextLoader`^] as the default `⚪ ContextLoader` when no specific {spring-api-spec-url}/org/springframework/test/context/ContextConfiguration.html[`@ContextConfiguration(loader=...)`^] is defined.
* Automatically searches for a `@SpringBootConfiguration` when nested `@Configuration` is not used, and no explicit classes are specified.
* Allows custom Environment properties to be defined using the `properties` attribute.
* Allows application arguments to be defined using the `args` attribute.
* Provides support for different `webEnvironment` modes, including the ability to start a fully running web server listening on a defined or random port
* Registers a {spring-boot-api-spec-url}/org/springframework/boot/test/web/client/TestRestTemplate.html[`🟢 TestRestTemplate`^] and/or {spring-api-spec-url}/org/springframework/test/web/reactive/server/WebTestClient.html[`⚪ WebTestClient`^] bean for use in web tests that are using a fully running web server

.`@SpringBootTest` example
[,java]
----
@SpringBootTest
class BookControllerIT {
    @Autowired
    BookController bookController;

    @Test
    void testController() {
        // Assertions
    }
}
----
