= Spring Data JPA

image:https://img.shields.io/badge/Spring%20Documentation-2088E9?logo=quickLook&logoColor[link="https://docs.spring.io/spring-data/jpa/reference/jpa.html",window=_blank]
image:https://img.shields.io/badge/Spring%20Boot%20Documentation-2088E9?logo=quickLook&logoColor[link="https://docs.spring.io/spring-boot/reference/data/sql.html#data.sql.jpa-and-spring-data",window=_blank]

== Maven Dependency

[,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----

== Database Entity

In `domain` package you can define a Database Entity:

[,java]
----
@Entity // <1>
public class Author {

    @Id // <2>
    @GeneratedValue(strategy = GenerationType.AUTO) // <3>
    private Long id;

    private String firstName;

    private String lastName;

    @ManyToMany(mappedBy = "authors") // <4>
    private Set<Book> books; // <5>

    // Getters and Setters, toString(), equals(Object obj) and hashCode()

}
----
<1> {jakarta-ee-api-spec-url}/jakarta/persistence/entity[`@Entity`^] specifies that the class is a Database Entity
<2> {jakarta-ee-api-spec-url}/jakarta/persistence/id[`@Id`^] specifies the primary key of an Entity
<3> {jakarta-ee-api-spec-url}/jakarta/persistence/generatedvalue[`@GeneratedValue`^] specifies the generation strategy for the value of primary key. `AUTO` indicates that the persistence provider should pick an appropriate strategy for the particular database. See {jakarta-ee-api-spec-url}/jakarta/persistence/generationtype[`🟣 GenerationType`^] for other generation strategies.
<4> {jakarta-ee-api-spec-url}/jakarta/persistence/manytomany[`@ManyToMany`^] specifies a many-valued association with many-to-many multiplicity. The `mappedBy` is a field that owns the relationship.
<5> `⚪ Set<E>` is preferred here as each element will be unique

[,java]
----
@Entity
public class Book {

    // ...

    @ManyToMany
    @JoinTable(name = "author_book", // <1>
        joinColumns = @JoinColumn(name = "book_id"), // <2>
        inverseJoinColumns = @JoinColumn(name = "author_id")) // <3>
    private Set<Author> authors;

    // ...

}
----
<1> {jakarta-ee-api-spec-url}/jakarta/persistence/jointable[`@JoinTable`^] specifies the mapping of associations. It is applied to the *owning side of an association*. The `name` is a name of the join table
<2> The `joinColumns` is a {jakarta-ee-api-spec-url}/jakarta/persistence/joincolumn[`@JoinColumn`^] array of the *foreign key columns* of the join table which reference the primary table of the entity *owning the association*
<3> The `inverseJoinColumns` is a `@JoinColumn` array of the *foreign key columns* of the join table which reference the primary table of the entity that *does not own the association*.

== Repository

When we run the application, Spring Data JPA is going to *provide* us a Repository *implementation*. It means that we only have to define a Repository interface.

[,java]
----
public interface AuthorRepository extends CrudRepository<Author, Long> {} // <1>
----
<1> {spring-data-api-spec-url}/org/springframework/data/repository/CrudRepository.html[`⚪ CrudRepository<I,ID>`^] is for generic CRUD operations on a Repository for a specific type
* `T` is the domain type the Repository manages.
* `ID` is the type of the id of the Entity the Repository manages
